# NUMPY - Numerical Python

In [2]:
# Importing numpy
import numpy as np

In [5]:
# Numpy array are homogeneous
a = np.array([3,4,5,6])
a

array([3, 4, 5, 6])

In [6]:
print(a)
print("Dimension : ",a.ndim)
print("Size : ",a.size)
print("Element Type : ",a.dtype)

[3 4 5 6]
Dimension :  1
Size :  4
Element Type :  int32


In [136]:
# Create a 2-D Array
a = np.array([[3,4,5],[6,7,8]])
a

array([[3, 4, 5],
       [6, 7, 8]])

In [137]:
print(a)
print("Dimension : ",a.ndim)
print("Size : ",a.size)
print("Element Type : ",a.dtype)

[[3 4 5]
 [6 7 8]]
Dimension :  2
Size :  6
Element Type :  int32


## Task: Create (2,3,2)
- Reading it from right to left
- The first digit (2) tells as that there should 2 elements in 1-Dimension
- The second digit (3) tells as that there should 3 elements in 2-Dimension
- The third digit (2) tells as that there should 2 elements in 3-Dimension

- 1-D: [2,3]
- 2-D: [[2,3],[4,5],[6,7]]
- 3-D: [[[2,3],[4,5],[6,7]],[[2,3],[4,5],[6,7]]]


In [25]:
a = np.array([[[2,3],[4,5],[6,7]],[[2,3],[4,5],[6,7]]])

In [26]:
print(a)
print("Dimension : ",a.ndim)
print("Size : ",a.size)
print("Shape : ",a.shape)
print("Element Type : ",a.dtype)

[[[2 3]
  [4 5]
  [6 7]]

 [[2 3]
  [4 5]
  [6 7]]]
Dimension :  3
Size :  12
Shape :  (2, 3, 2)
Element Type :  int32


In [29]:
a = np.array([
                [[2,3],
                 [4,5],
                 [6,7]],
    
                [[2,3],
                 [4,5],
                 [6,7]]
    
                ])

## Arange

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(24).reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [36]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
np.zeros((2,2)) # Creates an array full of zeroes

array([[0., 0.],
       [0., 0.]])

In [49]:
np.linspace(10,50,5) #linspace(start,end,no.of elements)
# Equally spaced sample data

array([10., 20., 30., 40., 50.])

In [52]:
np.linspace(1,25,5)

array([ 1.,  7., 13., 19., 25.])

## Reshape

In [54]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [55]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Create a six dimentional data with arange having 6 elements in 1-dimension

In [56]:
np.arange(720).reshape(1,2,3,4,5,6)

array([[[[[[  0,   1,   2,   3,   4,   5],
           [  6,   7,   8,   9,  10,  11],
           [ 12,  13,  14,  15,  16,  17],
           [ 18,  19,  20,  21,  22,  23],
           [ 24,  25,  26,  27,  28,  29]],

          [[ 30,  31,  32,  33,  34,  35],
           [ 36,  37,  38,  39,  40,  41],
           [ 42,  43,  44,  45,  46,  47],
           [ 48,  49,  50,  51,  52,  53],
           [ 54,  55,  56,  57,  58,  59]],

          [[ 60,  61,  62,  63,  64,  65],
           [ 66,  67,  68,  69,  70,  71],
           [ 72,  73,  74,  75,  76,  77],
           [ 78,  79,  80,  81,  82,  83],
           [ 84,  85,  86,  87,  88,  89]],

          [[ 90,  91,  92,  93,  94,  95],
           [ 96,  97,  98,  99, 100, 101],
           [102, 103, 104, 105, 106, 107],
           [108, 109, 110, 111, 112, 113],
           [114, 115, 116, 117, 118, 119]]],


         [[[120, 121, 122, 123, 124, 125],
           [126, 127, 128, 129, 130, 131],
           [132, 133, 134, 135, 136, 137],
 

In [63]:
d = np.arange(6).reshape(1,1,1,1,1,6)
d

array([[[[[[0, 1, 2, 3, 4, 5]]]]]])

# Ravel

In [64]:
d.ravel()

array([0, 1, 2, 3, 4, 5])

## Random Numbers

In [72]:
np.random.rand()*100

52.79070791311403

In [75]:
int(np.random.rand()*100)

91

In [3]:
np.random.rand(5)

array([0.00976184, 0.31091601, 0.55021368, 0.828186  , 0.99124151])

In [4]:
np.random.randint(35,100)

35

In [81]:
np.random.randint(35,100,50).reshape(5,10)

array([[36, 47, 40, 55, 84, 59, 82, 49, 96, 95],
       [42, 92, 88, 45, 66, 64, 88, 44, 77, 91],
       [69, 73, 72, 65, 72, 75, 75, 36, 89, 65],
       [62, 45, 37, 90, 65, 66, 46, 47, 86, 66],
       [69, 99, 47, 56, 40, 82, 55, 55, 63, 79]])

In [82]:
(np.random.randint(35,100,50).reshape(5,10))**2

array([[4096, 6241, 5776, 5625, 7396, 5184, 7744, 8836, 3136, 5929],
       [9801, 8464, 9801, 9604, 6084, 4900, 1936, 5476, 6724, 3364],
       [8836, 1444, 1444, 6724, 1849, 7225, 1369, 9409, 3481, 9604],
       [7744, 4096, 1681, 2704, 2809, 2116, 2916, 7744, 4225, 3844],
       [1600, 5184, 4489, 1521, 5041, 2025, 8836, 7744, 3721, 1296]],
      dtype=int32)

In [83]:
np.sqrt(np.random.randint(35,100,50).reshape(5,10))

array([[7.68114575, 9.16515139, 7.07106781, 9.21954446, 9.05538514,
        7.68114575, 7.74596669, 9.38083152, 7.87400787, 7.28010989],
       [9.48683298, 9.        , 8.42614977, 7.41619849, 6.78232998,
        6.        , 6.70820393, 7.41619849, 6.55743852, 7.14142843],
       [9.32737905, 6.55743852, 9.        , 8.60232527, 9.74679434,
        9.48683298, 6.08276253, 6.63324958, 5.91607978, 8.24621125],
       [9.2736185 , 8.60232527, 7.87400787, 6.08276253, 7.48331477,
        8.42614977, 8.24621125, 8.83176087, 9.43398113, 8.06225775],
       [8.94427191, 7.68114575, 7.54983444, 7.07106781, 8.36660027,
        6.63324958, 7.14142843, 7.41619849, 7.41619849, 5.91607978]])

In [84]:
np.random.randint(0,1000,1000000).reshape(1000,1000)

array([[929, 431, 228, ..., 333, 785, 377],
       [390, 362, 537, ..., 683, 256, 409],
       [303, 695,  42, ..., 589, 296, 859],
       ...,
       [332, 504, 383, ..., 887, 444, 944],
       [ 84, 903, 724, ..., 734, 366, 581],
       [367, 562, 445, ..., 503, 564, 534]])

In [86]:
np.sqrt(np.random.randint(0,1000,1000000).reshape(1000,1000))

array([[17.        , 25.33771892, 14.49137675, ..., 20.49390153,
        20.14944168, 10.72380529],
       [25.59296778,  3.16227766, 26.13426869, ..., 13.45362405,
        24.2693222 , 20.51828453],
       [23.21637353, 31.        , 26.32489316, ..., 10.95445115,
        22.75961335, 24.08318916],
       ...,
       [27.49545417, 28.74021573, 17.8325545 , ..., 12.84523258,
        24.49489743,  9.64365076],
       [ 9.94987437, 23.85372088, 25.3968502 , ..., 27.60434748,
        31.27299154, 29.49576241],
       [21.21320344, 17.49285568, 29.52964612, ..., 14.35270009,
        31.01612484, 30.82207001]])

In [87]:
np.round(4.6)

5.0

In [88]:
np.floor(4.6)

4.0

In [91]:
np.ceil(4.1)

5.0

In [92]:
np.log10(100)

2.0

## Horizontal and Vertical Split & Horizontal and Vertical Stack

### Horizontal and Vertical Split

In [95]:
a = np.arange(24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [96]:
np.hsplit(a,2)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [97]:
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [99]:
print(np.hsplit(a,2)[0])

[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]
 [18 19 20]]


In [100]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [101]:
print(np.vsplit(a,2)[0])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


### Horizontal and Vertical Stack

In [108]:
a = np.arange(9).reshape(3,3)
b = np.arange(9,18).reshape(3,3)
print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [109]:
np.hstack((a,b))

array([[ 0,  1,  2,  9, 10, 11],
       [ 3,  4,  5, 12, 13, 14],
       [ 6,  7,  8, 15, 16, 17]])

In [110]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

## Q: ADD two integers in an array and typecast it to float

In [113]:
a = np.random.randint(1,10,4).reshape(2,2)
a

array([[6, 4],
       [9, 5]])

In [114]:
b = np.random.randint(1,10,4).reshape(2,2)
b

array([[6, 8],
       [2, 1]])

In [127]:
c = a+b
c

array([[12, 12],
       [11,  6]])

In [126]:
print(c.astype(float))

[[12. 12.]
 [11.  6.]]


In [128]:
np.hsplit(a,2)

[array([[6],
        [9]]), array([[4],
        [5]])]

In [130]:
print((np.hsplit(a,2)[0])+(np.hsplit(a,2)[0]))

[[12]
 [18]]


In [134]:
x = np.array([4+5,8+9],dtype='float')
print(x)
x.dtype

[ 9. 17.]


dtype('float64')